version: '2'
services:
  webserver:
    image: phpstorm/php-71-apache-xdebug-26
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.41